version: '3'

tasks:
  start:
    desc: Start the backend in developer mode
    cmds:
      - docker-compose -p cps_nftstore_dev_backend -f dev.docker-compose.yml up --remove-orphans

  end:
    desc: Stop the backend in developer mode
    cmds:
      - docker-compose -p cps_nftstore_dev_backend -f dev.docker-compose.yml down

  console:
    desc: Open console in (developer mode) running backend
    cmds:
      - docker exec -it cps_nftstore_dev_backend bash

  wire:
    desc: Generate new compile-time dependency injection file, called `wire_gen.go`, which is needed by our app.
    cmds:
      - go run github.com/google/wire/cmd/wire

  clean:
    cmds:
      - go clean -cache
      - go clean -modcache

  vendor:
    desc: Save all the libraries into our code repository
    cmds:
      - go mod download
      - go mod vendor

  upgradelib:
    desc: Update all the golang libraries (https://stackoverflow.com/a/67202539)
    cmds:
      - go get -u ./...

  undelast:
    desc: Undue last commit which was not pushed. Special thanks to https://www.nobledesktop.com/learn/git/undo-changes.
    cmds:
      - git reset --soft HEAD~

  genkey:
    desc: Generate a unique key.
    cmds:
      - openssl rand -hex 64.

  startlinux:
    desc: Build project using linux containerization and start the backend in production mode.
    cmds:
      - docker-compose -p cps_nftstore_prod_backend -f prod.docker-compose.yml up --remove-orphans
