// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDataDirectoryFromDialog() {
  return window['go']['main']['App']['GetDataDirectoryFromDialog']();
}

export function GetDataDirectoryFromPreferences() {
  return window['go']['main']['App']['GetDataDirectoryFromPreferences']();
}

export function GetDefaultDataDirectory() {
  return window['go']['main']['App']['GetDefaultDataDirectory']();
}

export function SaveDataDirectory(arg1) {
  return window['go']['main']['App']['SaveDataDirectory'](arg1);
}

export function ShutdownApp() {
  return window['go']['main']['App']['ShutdownApp']();
}
