// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDataDirectoryFromDialog():Promise<string>;

export function GetPageID():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SaveDataDirectory(arg1:string):Promise<void>;
