// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDataDirectoryFromDialog() {
  return window['go']['main']['App']['GetDataDirectoryFromDialog']();
}

export function GetPageID() {
  return window['go']['main']['App']['GetPageID']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveDataDirectory(arg1) {
  return window['go']['main']['App']['SaveDataDirectory'](arg1);
}
