version: "3"

tasks:
  initworkspace:
    desc: (Do not run) Init the go workspace
    cmds:
      - go work init

  updateworkspace:
    desc: Update the go workspace for this project
    cmds:
      - go work use -r .

  usecps:
    desc: Load up the go workspace for the `cps-backend` module.
    cmds:
      - go work use ./cloud/cps-backend

  useipfs:
    desc: Load up the go workspace for the `cps-ipfsstore-backend` module.
    cmds:
      - go work use ./cloud/cps-ipfsstore-backend

  usenft:
    desc: Load up the go workspace for the `cps-nftstore-backend` module.
    cmds:
      - go work use ./cloud/cps-nftstore-backend

  usenftcli:
    desc: Load up the go workspace for the `cps-nftstore-cli` module.
    cmds:
      - go work use ./cloud/cps-nftstore-cli
