version: "3"

tasks:
  initworkspace:
    desc: (Do not run) Init the go workspace
    cmds:
      - go work init

  updateworkspace:
    desc: Update the go workspace for this project
    cmds:
      - go work use -r .

  usecps:
    desc: Load up the go workspace for the `cps-backend` module.
    cmds:
      - go work use ./cloud/cps-backend

  usecomiccoin:
    desc: Load up the go workspace for the `comiccoin` module.
    cmds:
      - go work use ./native/desktop/comiccoin

  usenftstore:
    desc: Load up the go workspace for the `comiccoin-nftstore` module.
    cmds:
      - go work use ./native/desktop/comiccoin-nftstore

  useregistry:
    desc: Load up the go workspace for the `comiccoin-registry` module.
    cmds:
      - go work use ./native/desktop/comiccoin-registry
