// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/LuchaComics/monorepo/cloud/cps-backend/adapter/cache/mongodbcache"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/adapter/emailer/mailgun"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/adapter/paymentprocessor/stripe"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/adapter/pdfbuilder"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/adapter/storage/mongodb"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/adapter/storage/s3"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/adapter/templatedemailer"
	controller6 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/attachment/controller"
	datastore5 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/attachment/datastore"
	httptransport6 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/attachment/httptransport"
	controller4 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/comicsub/controller"
	datastore3 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/comicsub/datastore"
	httptransport4 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/comicsub/httptransport"
	controller10 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/credit/controller"
	datastore4 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/credit/datastore"
	httptransport10 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/credit/httptransport"
	controller5 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/customer/controller"
	httptransport5 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/customer/httptransport"
	datastore9 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/eventlog/datastore"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/app/gateway/controller"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/app/gateway/httptransport"
	controller7 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/offer/controller"
	datastore8 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/offer/datastore"
	httptransport7 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/offer/httptransport"
	stripe2 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/paymentprocessor/controller/stripe"
	stripe3 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/paymentprocessor/httptransport/stripe"
	controller8 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/receipt/controller"
	datastore6 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/receipt/datastore"
	httptransport8 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/receipt/httptransport"
	controller3 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/store/controller"
	datastore2 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/store/datastore"
	httptransport3 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/store/httptransport"
	controller2 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/user/controller"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/app/user/datastore"
	httptransport2 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/user/httptransport"
	controller9 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/userpurchase/controller"
	datastore7 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/userpurchase/datastore"
	httptransport9 "github.com/LuchaComics/monorepo/cloud/cps-backend/app/userpurchase/httptransport"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/config"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/inputport/http"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/inputport/http/middleware"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/provider/blacklist"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/provider/cpsrn"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/provider/jwt"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/provider/kmutex"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/provider/logger"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/provider/password"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/provider/time"
	"github.com/LuchaComics/monorepo/cloud/cps-backend/provider/uuid"
)

import (
	_ "go.uber.org/automaxprocs"
	_ "time/tzdata"
)

// Injectors from wire.go:

func InitializeEvent() Application {
	slogLogger := logger.NewProvider()
	conf := config.New()
	provider := uuid.NewProvider()
	timeProvider := time.NewProvider()
	jwtProvider := jwt.NewProvider(conf)
	blacklistProvider := blacklist.NewProvider()
	kmutexProvider := kmutex.NewProvider()
	passwordProvider := password.NewProvider()
	client := mongodb.NewStorage(conf, slogLogger)
	cacher := mongodbcache.NewCache(conf, slogLogger, client)
	emailer := mailgun.NewEmailer(conf, slogLogger, provider)
	templatedEmailer := templatedemailer.NewTemplatedEmailer(conf, slogLogger, provider, emailer)
	paymentProcessor := stripe.NewPaymentProcessor(conf, slogLogger, provider)
	userStorer := datastore.NewDatastore(conf, slogLogger, client)
	storeStorer := datastore2.NewDatastore(conf, slogLogger, client)
	gatewayController := controller.NewController(conf, slogLogger, provider, jwtProvider, kmutexProvider, passwordProvider, cacher, client, templatedEmailer, paymentProcessor, userStorer, storeStorer)
	middlewareMiddleware := middleware.NewMiddleware(conf, slogLogger, provider, timeProvider, jwtProvider, blacklistProvider, gatewayController)
	handler := httptransport.NewHandler(slogLogger, gatewayController)
	comicSubmissionStorer := datastore3.NewDatastore(conf, slogLogger, client)
	creditStorer := datastore4.NewDatastore(conf, slogLogger, client)
	attachmentStorer := datastore5.NewDatastore(conf, slogLogger, client)
	receiptStorer := datastore6.NewDatastore(conf, slogLogger, client)
	userPurchaseStorer := datastore7.NewDatastore(conf, slogLogger, client)
	userController := controller2.NewController(conf, slogLogger, provider, passwordProvider, client, storeStorer, userStorer, comicSubmissionStorer, creditStorer, attachmentStorer, receiptStorer, userPurchaseStorer, templatedEmailer)
	httptransportHandler := httptransport2.NewHandler(slogLogger, userController)
	s3Storager := s3.NewStorage(conf, slogLogger, provider)
	storeController := controller3.NewController(conf, slogLogger, provider, s3Storager, emailer, templatedEmailer, client, storeStorer, userStorer, comicSubmissionStorer, creditStorer, attachmentStorer, receiptStorer, userPurchaseStorer)
	handler2 := httptransport3.NewHandler(slogLogger, storeController)
	cpsrnProvider := cpsrn.NewProvider()
	cbffBuilder := pdfbuilder.NewCBFFBuilder(conf, slogLogger, provider)
	pcBuilder := pdfbuilder.NewPCBuilder(conf, slogLogger, provider)
	ccimgBuilder := pdfbuilder.NewCCIMGBuilder(conf, slogLogger, provider)
	ccscBuilder := pdfbuilder.NewCCSCBuilder(conf, slogLogger, provider)
	ccBuilder := pdfbuilder.NewCCBuilder(conf, slogLogger, provider)
	ccugBuilder := pdfbuilder.NewCCUGBuilder(conf, slogLogger, provider)
	comicSubmissionController := controller4.NewController(conf, slogLogger, provider, s3Storager, passwordProvider, kmutexProvider, cpsrnProvider, cbffBuilder, pcBuilder, ccimgBuilder, ccscBuilder, ccBuilder, ccugBuilder, emailer, client, templatedEmailer, userStorer, comicSubmissionStorer, storeStorer, creditStorer)
	handler3 := httptransport4.NewHandler(slogLogger, comicSubmissionController)
	customerController := controller5.NewController(conf, slogLogger, provider, s3Storager, passwordProvider, paymentProcessor, cbffBuilder, templatedEmailer, client, userStorer, comicSubmissionStorer)
	handler4 := httptransport5.NewHandler(slogLogger, customerController)
	attachmentController := controller6.NewController(conf, slogLogger, provider, s3Storager, emailer, client, attachmentStorer, userStorer, comicSubmissionStorer)
	handler5 := httptransport6.NewHandler(slogLogger, attachmentController)
	offerStorer := datastore8.NewDatastore(conf, slogLogger, client)
	offerontroller := controller7.NewController(conf, slogLogger, provider, client, paymentProcessor, storeStorer, offerStorer, userStorer)
	handler6 := httptransport7.NewHandler(slogLogger, offerontroller)
	receiptController := controller8.NewController(conf, slogLogger, provider, client, storeStorer, receiptStorer)
	handler7 := httptransport8.NewHandler(slogLogger, receiptController)
	userPurchaseController := controller9.NewController(conf, slogLogger, provider, client, storeStorer, userPurchaseStorer)
	handler8 := httptransport9.NewHandler(slogLogger, userPurchaseController)
	eventLogStorer := datastore9.NewDatastore(conf, slogLogger, client)
	stripePaymentProcessorController := stripe2.NewController(conf, slogLogger, provider, s3Storager, passwordProvider, emailer, templatedEmailer, paymentProcessor, kmutexProvider, client, storeStorer, userStorer, receiptStorer, offerStorer, eventLogStorer, comicSubmissionStorer, userPurchaseStorer)
	stripeHandler := stripe3.NewHandler(slogLogger, stripePaymentProcessorController)
	creditController := controller10.NewController(conf, slogLogger, provider, client, storeStorer, creditStorer, userStorer, offerStorer)
	handler9 := httptransport10.NewHandler(slogLogger, creditController)
	inputPortServer := http.NewInputPort(conf, slogLogger, middlewareMiddleware, handler, httptransportHandler, handler2, handler3, handler4, handler5, handler6, handler7, handler8, stripeHandler, handler9)
	application := NewApplication(slogLogger, inputPortServer)
	return application
}
