version: "3"

tasks:
  desc: "start the project (for web-development only)"
  start:
    cmds:
      - npm run start:dev

  # Note: Only executed by devops team.
  buildprod:
    desc: "build the production version of the project"
    cmds:
      - docker build -t cps_nftstore_frontend .

  startprod:
    cmds:
      - docker run --name cps_nftstore_prod_frontend -d -p 3000:80 cps_nftstore_frontend
