// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateNFT(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<domain.NFT>;

export function GetDataDirectoryFromDialog():Promise<string>;

export function GetDataDirectoryFromPreferences():Promise<string>;

export function GetDefaultDataDirectory():Promise<string>;

export function GetImageFilePathFromDialog():Promise<string>;

export function GetNFTs():Promise<Array<domain.NFT>>;

export function GetVideoFilePathFromDialog():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SaveDataDirectory(arg1:string):Promise<void>;

export function ShutdownApp():Promise<void>;
