// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNFT(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateNFT'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function GetDataDirectoryFromDialog() {
  return window['go']['main']['App']['GetDataDirectoryFromDialog']();
}

export function GetDataDirectoryFromPreferences() {
  return window['go']['main']['App']['GetDataDirectoryFromPreferences']();
}

export function GetDefaultDataDirectory() {
  return window['go']['main']['App']['GetDefaultDataDirectory']();
}

export function GetImageFilePathFromDialog() {
  return window['go']['main']['App']['GetImageFilePathFromDialog']();
}

export function GetNFTs() {
  return window['go']['main']['App']['GetNFTs']();
}

export function GetVideoFilePathFromDialog() {
  return window['go']['main']['App']['GetVideoFilePathFromDialog']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveDataDirectory(arg1) {
  return window['go']['main']['App']['SaveDataDirectory'](arg1);
}

export function ShutdownApp() {
  return window['go']['main']['App']['ShutdownApp']();
}
