// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDataDirectoryFromDialog():Promise<string>;

export function GetDataDirectoryFromPreferences():Promise<string>;

export function GetDefaultDataDirectory():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SaveDataDirectory(arg1:string):Promise<void>;

export function ShutdownApp():Promise<void>;

export function StartupApp():Promise<void>;
